### ISSUE TITLE
Add function to filter rules by type

### ISSUE THREAD

**Issue by edwindj** [data-cleaning/errorlocate#2]
types currently are:
- linear
- categorical
- conditional

**Comment by markvanderloo** [comment]
These are subcategories of rules that are 1) record-wise executable and 2)
allow error localization with known algorithms. We may want to have a
general function that selects rules that are apt for error localization and
use the further categorization internally only. This would allow for
extension if new/better algorithms become available.

**Comment by edwindj** [comment]
It should be extensible indeed:
I'm thinking of a subscription pattern. One or multiple errorlocalizer could be registered to find errors. Each errorlocalizer will use a subset of the rules to find errors. Rules that are not used by any of the errorlocalizer are reported.

**Comment by edwindj** [comment]
Implemented
