### ISSUE TITLE
Rule assignments are not working

### ISSUE THREAD

**Issue by edwindj** [data-cleaning/errorlocate#20]
Rule assignment are not working, see e.g. issue #19

**Comment by markvanderloo** [comment]
Should be easy fix: 

```r
> v <- validator(m := median(x), x < 3* m)
> v$exprs(expand_assignments=TRUE)
$V2
x < 3 * median(x)
```

**Comment by edwindj** [comment]
I knew the setting :-), but not as easily fixable:

The errorlocate operates on the validator object and uses its selection mechanism to exclude rules that are not linear, categorical or conditinal. Assignments are neither. 

There is (currently) a schism between rules and exprs:
- rules with var_group statements are macro/metarules that have to be expanded.
- assignments are not rules as such, but stored as a rule in the validator object.
This is fine, but can give problems when operating on the rules, because selection does not work upon the (expanded) rules, but on the specifications.

 is_linear, is_categorical and is_conditional currently work upon the validator object, reporting back which  (meta)rule is linear, categorical, conditional. Working upon the expr would change the length/position of the logical.  Will change that, but trying to figure out, what the nicest option for doing that is. 
I think an utility function that creates a new validator object in which assignments and var_groups have been expanded, would be helpful in doing that.

**Comment by edwindj** [comment]
Possible quick solution (working on that):

- expand validator to exprs
- change is_linear, is_conditional, is_categorical (also) operate on vectors of expression

**Comment by edwindj** [comment]
Fixed
