### ISSUE TITLE
feat: support `validate::in_range` 

### ISSUE THREAD

**Issue by edwindj** [data-cleaning/errorlocate#33]
`validate` version 1.0 introduced some new commands to facilitate validation of records. 
Some of those constructs can (and should) be translated into linear constraints in `errorlocate`.

`in_range` can be translated into two linear boundary conditions.

**Comment by peterlevy** [comment]
Almost all my rules are expressed using `in_range` so this would be really useful.  Any idea when you might do this, or should I rewrite my rules as separate min and max rules? I love the package.

**Comment by edwindj** [comment]
Thanks for you reminder :-).  I will add this today in the github repo.

But it will take two weeks before I will release it on CRAN, since I released a version last week and want to test the other features I have been adding.

Hope that won't block your working flow!

Best, 

Edwin

**Comment by edwindj** [comment]
`in_range`  support is merged into the main branch
